Initialized Next.js 15 in Existing Repo; Added Hero and Navbar Components
frc-7419/7419tech pull request #3
Opened 2024-11-09 02:20 UTC by Arbitr-ary-ily

2024-11-09 02:27 UTC, Jolteous reviewed
Looks good to me, I'm going to let @MostOriginalIGN look at this as well, there may be some room for growth so updates in the future are more streamlined.

2024-11-09 07:45 UTC, MostOriginalIGN approved these changes, later dismissed
Looks great and organized. But no please do not push an env file if needed. It will never be needed. 

Also why did the read me change, otherwise its all good.

2024-11-09 07:46 UTC, MostOriginalIGN commented
Okay wait nextjs ci deleted???

2024-11-09 07:59 UTC, MostOriginalIGN requested changes
**Why was everything moved into a subdirectory?**
  - Having a subdirectory unnecessarily complicates the repo structure.
  - For ease of access and better organization, we should keep the main content at the root level.

**Why was the CI check for Next.js removed?**
  - Removing the CI check might compromise our ability to catch issues early.
  - CI checks ensure the project adheres to best practices and avoids regressions. Was there a specific reason for this removal?

**Package Manager Consistency**
  - Just making sure because I saw some changes mixing `npm` and `yarn` can lead to dependency resolution issues.
  - Let's stick to one package manager consistently across the project to avoid potential conflicts.

**Environment Variables**
  - Committing `.env` or `.env.local` files should never be optional.
  - These files can expose sensitive or development-only configurations.
  - Instead, we should use GitHub or Vercel environment variables for managing sensitive data securely.

Sorry these things weren't evident at first for me as I was on mobile.

2024-11-16 21:36 UTC, MostOriginalIGN reviewed
Everything looks good so far, except for the fact it cant build. I'm gonna re add the CI just in case. Also why is this still here 
<img width="592" alt="image" src="https://github.com/user-attachments/assets/41f7f453-a087-4339-9bfc-5528c796bb82">

2025-01-20 04:55 UTC, closed without merging